activity/urls.py
from django.urls import path

from . import views

app_name = 'activity'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('delete/<str:id>', views.delete, name='delete'),
    path('delete/member/<str:id>', views.delete_member, name='delete_member')
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('activity.urls'), name='activity')
]

activity/models.py
from django.db import models

# Create your models here.


class Activity(models.Model):
    activity = models.CharField(max_length=100)
    def __str__(self):
        return self.activity

class Member(models.Model):
    aktivitas = models.ForeignKey(Activity, on_delete=models.CASCADE)
    member = models.CharField(max_length=100)
    def __str__(self):
        return self.member

activity/forms.py
from django import forms
from .models import Activity, Member

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'activity' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Let's do something"}),
        }

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'
        widgets = {
            'member' : forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': "C'mon in!"})
        }

activity/views.py
from django.shortcuts import render,redirect
from .models import Member, Activity
from .forms import MemberForm ,ActivityForm
from django.contrib import messages
# Create your views here.

def activity(request):
    if request.method == "POST":
        formA = ActivityForm(request.POST)
        formB = MemberForm(request.POST)
        if formA.is_valid():
            formA.save()
            return redirect('activity:activity')
        elif formB.is_valid():
            formB.save()
            return redirect('activity:activity')
    else:
        formA = ActivityForm()
        formB = MemberForm()
        activities = Activity.objects.all()
        members = Member.objects.all()
        context = {
            'formA' : formA,
            'formB' : formB,
            'activities' : activities,
            'members' : members
        }
        return render(request, 'activity.html', context)

def delete(request,id):
    Activity.objects.get(id=id).delete()
    return redirect('activity:activity')

def delete_member(request,id):
    Member.objects.get(id=id).delete()
    return redirect('activity:activity')

activity/templates/activity.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>Welcome!</title>
</head>
<style>
body {
    background-color: #FFA69E;
    font-family: 'Poppins', sans-serif;
    padding-right: 10px;
    padding-left: 10px;
}
</style>

    <Form method="POST" class="row my-5">
        {% csrf_token %}
        <div class="col-7 ml-auto">
            {{ formA.activity }}
        </div>
        <button type="submit" class="btn btn-dark col-2 mr-auto">add activity</button>
    </Form>

    <hr>
    <p style="text-align: center; font-weight: bolder; font-size: 35px; margin-bottom: 0px;"> Fala's Cards </p>
    <p style="text-align: center; font-size: 20px; margin-bottom: 0px; "> follow me, or you'll miss good times in your life</p>
    <div class="d-flex justify-content-around flex-wrap pb-4">
        {% for activity in activities %}
        <div class="card bg-white mt-5" style="width: 18rem;">
            <div class="card-header">
                <div class="row">
                    <h5 class="col-10 mb-2">{{ activity }}</h5>
                    <a href="{% url 'activity:delete' activity.id %}" class="col-2">
                        <button type="button" class="close mb-2">&times;</button>
                    </a>
                </div>
            </div>


            <div class="card-body">
                <h6 class="card-title">my pals:</h6>
                <p></p>
                <ul>

                    {% for member in members %}
                    {% if member.aktivitas.id == activity.id %}
                    <li class="row">
                        <h5 class="col-10">{{ member }}</h5>
                        <a href="{% url 'activity:delete_member' member.id %}" class="col-2">
                            <button type="button" class="close">&times;</button>
                        </a>    
                    </li>
                    {% endif %}
                    {% endfor %}

                </ul>
                <form method="POST">
                    {% csrf_token %}
                    {{ formB.member }}
                    <input name="aktivitas" type="text" value="{{ activity.id }}" style="display: none;">
                    <button type="submit" class="btn btn-dark col-6 mt-2">I'm in</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    
</div>
<body>
    
</body>
</html>